USE [DaVinci_TEST]
GO

/****** Object:  StoredProcedure [dbo].[NutrientWorkAround]    Script Date: 07/21/2017 19:52:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[NutrientWorkAround] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    
UPDATE nd SET nd.NutrientValue = scode.[Added Sugar (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 148   and scode.[Added Sugar (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Alcohol (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 111   and scode.[Alcohol (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Ash (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 24   and scode.[Ash (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Water (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 23   and scode.[Water (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Mono Fat (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 19   and scode.[Mono Fat (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Organic Acids (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 122   and scode.[Organic Acids (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Poly Fat (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 20   and scode.[Poly Fat (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Protein (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 1   and scode.[Protein (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Saturated Fat (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 18   and scode.[Saturated Fat (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Sugar Alcohol (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 116   and scode.[Sugar Alcohol (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Fat (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 17   and scode.[Fat (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Trans Fatty Acid (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 21   and scode.[Trans Fatty Acid (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Calories (kcal)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 0   and scode.[Calories (kcal)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Chromium (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 49   and scode.[Chromium (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Folic Acid (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 181   and scode.[Folic Acid (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Beta-Carotene (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 29   and scode.[Beta-Carotene (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin K (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 44   and scode.[Vitamin K (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Caffeine (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 112   and scode.[Caffeine (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Calcium (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 47   and scode.[Calcium (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Chloride (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 48   and scode.[Chloride (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Cholesterol (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 22   and scode.[Cholesterol (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Choline (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 127   and scode.[Choline (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Copper (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 50   and scode.[Copper (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Fluoride (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 51   and scode.[Fluoride (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Iron (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 53   and scode.[Iron (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Magnesium (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 54   and scode.[Magnesium (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Manganese (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 55   and scode.[Manganese (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Phosphorus (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 57   and scode.[Phosphorus (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Potassium (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 58   and scode.[Potassium (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B2 (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 31   and scode.[Vitamin B2 (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Sodium (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 60   and scode.[Sodium (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B1 (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 30   and scode.[Vitamin B1 (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin C (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 37   and scode.[Vitamin C (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin E - mg (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 42   and scode.[Vitamin E - mg (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Zinc (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 61   and scode.[Zinc (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Total Insoluble Fiber (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 4   and scode.[Total Insoluble Fiber (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Insoluble Fiber (2016) (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 210   and scode.[Insoluble Fiber (2016) (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Total Soluble Fiber (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 4   and scode.[Total Soluble Fiber (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Soluble Fiber (2016) (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 209   and scode.[Soluble Fiber (2016) (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B6 (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 34   and scode.[Vitamin B6 (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B6 (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 34   and scode.[Vitamin B6 (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Folate (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 43   and scode.[Folate (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Folate, DFE (mcg DFE)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 183   and scode.[Folate, DFE (mcg DFE)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B3 (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 32   and scode.[Vitamin B3 (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B3 - Niacin Equiv (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 33   and scode.[Vitamin B3 - Niacin Equiv (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin A - IU (IU)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 25   and scode.[Vitamin A - IU (IU)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin A - IU (IU)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 25   and scode.[Vitamin A - IU (IU)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Carbohydrates (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 2   and scode.[Carbohydrates (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Total Sugars (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 6   and scode.[Total Sugars (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Pantothenic Acid (mg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 45   and scode.[Pantothenic Acid (mg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Total Dietary Fiber (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 3   and scode.[Total Dietary Fiber (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Dietary Fiber (2016) (g)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 208   and scode.[Dietary Fiber (2016) (g)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Iodine (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 52   and scode.[Iodine (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Selenium (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 59   and scode.[Selenium (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Biotin (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 36   and scode.[Biotin (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin B12 (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 35   and scode.[Vitamin B12 (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin D - mcg (mcg)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 39   and scode.[Vitamin D - mcg (mcg)] is not null
UPDATE nd SET nd.NutrientValue = scode.[Vitamin D - IU (IU)] from gendata.dbo.basefoodnutrientdata nd join gendata.dbo.basefoodname fn on nd.NutrientRefNum = fn.NutrientRefNum join gendata.dbo.basefoodusercode uc on uc.primarykey = fn.PrimaryKey join t_ko_genesis_scodestagingtable scode on scode.usercode = uc.usercode WHERE nd.nutrientkey = 38   and scode.[Vitamin D - IU (IU)] is not null

    
    
    
    
    
    
    
    
    


END

GO

